### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by AbdElhalim12** [erichVK5/inkscape2pcb#5]
I got this error after I try to save either lht or fb format 

> Traceback (most recent call last):
>   File "geda_pcb_output.py", line 114, in <module>
>     MyEffect().run()
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\base.py", line 123, in run
>     self.save_raw(self.effect())
>   File "geda_pcb_output.py", line 110, in effect
>     self.process_group(doc)
>   File "geda_pcb_output.py", line 87, in process_group
>     if child.is_visible():
>   File "C:\Program Files\Inkscape\share\inkscape\extensions\inkex\elements\_base.py", line 147, in __getattr__
>     raise AttributeError("Can't find attribute {}.{}".format(self.typename, name))
> AttributeError: Can't find attribute Layer.is_visible

**Comment by erichVK5** [comment]
Thanks for the bug report.

Which version of inkscape are you using?

I have tested on 0.9x and 1.1.

I will try to duplicate your error, and feel free to provide an example inkscape file for failed export.

Cheers,

Erich
